---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [Gemfile, Gemfile.lock, CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Jsondb A Opensource, Java-based, In-Memory/Embedded, Securable database"
keywords:    "Jsondb, Java-based, In-Memory, Embedded, Filebased, Database, Encryption-Support, XPATH based Query, Opensource, MIT License"
description: "JsonDB is a Opensource, Java-based, In-Memory/Embedded, Database that stores its data as Json Files, with encryption support."
source_link: "https://github.com/Jsondb/jsondb-core"
url:         "http://jsondb.io" # the base hostname & protocol for your site
favicon:     "img/favicon-database.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-86156909-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
